version: '3'
services:
  simple:
    build: 
      context: .
      dockerfile: simple.Dockerfile
    ports:
      - 4000:80
  route:
    build: 
      context: .
      dockerfile: router.Dockerfile
    ports:
      - 3000:80
  obs:
    build:
      context: .
      dockerfile: obs.Dockerfile
      args:
        - OBS_ACCESS_KEY_ID
        - OBS_SECRET_ACCESS_KEY
        - ENDPOINT=obs.cn-south-1.myhuaweicloud.com
    ports:
      - 8000:80